// Code generated by MockGen. DO NOT EDIT.
// Source: proto/messagebus.pb.go

// Package mock_proto is a generated GoMock package.
package mock_proto

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	empty "github.com/golang/protobuf/ptypes/empty"
	proto "github.com/vardius/pubsub/proto"
	grpc "google.golang.org/grpc"
	metadata "google.golang.org/grpc/metadata"
)

// MockMessageBusClient is a mock of MessageBusClient interface
type MockMessageBusClient struct {
	ctrl     *gomock.Controller
	recorder *MockMessageBusClientMockRecorder
}

// MockMessageBusClientMockRecorder is the mock recorder for MockMessageBusClient
type MockMessageBusClientMockRecorder struct {
	mock *MockMessageBusClient
}

// NewMockMessageBusClient creates a new mock instance
func NewMockMessageBusClient(ctrl *gomock.Controller) *MockMessageBusClient {
	mock := &MockMessageBusClient{ctrl: ctrl}
	mock.recorder = &MockMessageBusClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMessageBusClient) EXPECT() *MockMessageBusClientMockRecorder {
	return m.recorder
}

// Publish mocks base method
func (m *MockMessageBusClient) Publish(ctx context.Context, in *proto.PublishRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Publish", varargs...)
	ret0, _ := ret[0].(*empty.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Publish indicates an expected call of Publish
func (mr *MockMessageBusClientMockRecorder) Publish(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockMessageBusClient)(nil).Publish), varargs...)
}

// Subscribe mocks base method
func (m *MockMessageBusClient) Subscribe(ctx context.Context, in *proto.SubscribeRequest, opts ...grpc.CallOption) (proto.MessageBus_SubscribeClient, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Subscribe", varargs...)
	ret0, _ := ret[0].(proto.MessageBus_SubscribeClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Subscribe indicates an expected call of Subscribe
func (mr *MockMessageBusClientMockRecorder) Subscribe(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockMessageBusClient)(nil).Subscribe), varargs...)
}

// MockMessageBus_SubscribeClient is a mock of MessageBus_SubscribeClient interface
type MockMessageBus_SubscribeClient struct {
	ctrl     *gomock.Controller
	recorder *MockMessageBus_SubscribeClientMockRecorder
}

// MockMessageBus_SubscribeClientMockRecorder is the mock recorder for MockMessageBus_SubscribeClient
type MockMessageBus_SubscribeClientMockRecorder struct {
	mock *MockMessageBus_SubscribeClient
}

// NewMockMessageBus_SubscribeClient creates a new mock instance
func NewMockMessageBus_SubscribeClient(ctrl *gomock.Controller) *MockMessageBus_SubscribeClient {
	mock := &MockMessageBus_SubscribeClient{ctrl: ctrl}
	mock.recorder = &MockMessageBus_SubscribeClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMessageBus_SubscribeClient) EXPECT() *MockMessageBus_SubscribeClientMockRecorder {
	return m.recorder
}

// Recv mocks base method
func (m *MockMessageBus_SubscribeClient) Recv() (*proto.SubscribeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*proto.SubscribeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv
func (mr *MockMessageBus_SubscribeClientMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockMessageBus_SubscribeClient)(nil).Recv))
}

// Header mocks base method
func (m *MockMessageBus_SubscribeClient) Header() (metadata.MD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header
func (mr *MockMessageBus_SubscribeClientMockRecorder) Header() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockMessageBus_SubscribeClient)(nil).Header))
}

// Trailer mocks base method
func (m *MockMessageBus_SubscribeClient) Trailer() metadata.MD {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer indicates an expected call of Trailer
func (mr *MockMessageBus_SubscribeClientMockRecorder) Trailer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockMessageBus_SubscribeClient)(nil).Trailer))
}

// CloseSend mocks base method
func (m *MockMessageBus_SubscribeClient) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend
func (mr *MockMessageBus_SubscribeClientMockRecorder) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockMessageBus_SubscribeClient)(nil).CloseSend))
}

// Context mocks base method
func (m *MockMessageBus_SubscribeClient) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context
func (mr *MockMessageBus_SubscribeClientMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockMessageBus_SubscribeClient)(nil).Context))
}

// SendMsg mocks base method
func (m_2 *MockMessageBus_SubscribeClient) SendMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg
func (mr *MockMessageBus_SubscribeClientMockRecorder) SendMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockMessageBus_SubscribeClient)(nil).SendMsg), m)
}

// RecvMsg mocks base method
func (m_2 *MockMessageBus_SubscribeClient) RecvMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg
func (mr *MockMessageBus_SubscribeClientMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockMessageBus_SubscribeClient)(nil).RecvMsg), m)
}

// MockMessageBusServer is a mock of MessageBusServer interface
type MockMessageBusServer struct {
	ctrl     *gomock.Controller
	recorder *MockMessageBusServerMockRecorder
}

// MockMessageBusServerMockRecorder is the mock recorder for MockMessageBusServer
type MockMessageBusServerMockRecorder struct {
	mock *MockMessageBusServer
}

// NewMockMessageBusServer creates a new mock instance
func NewMockMessageBusServer(ctrl *gomock.Controller) *MockMessageBusServer {
	mock := &MockMessageBusServer{ctrl: ctrl}
	mock.recorder = &MockMessageBusServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMessageBusServer) EXPECT() *MockMessageBusServerMockRecorder {
	return m.recorder
}

// Publish mocks base method
func (m *MockMessageBusServer) Publish(arg0 context.Context, arg1 *proto.PublishRequest) (*empty.Empty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", arg0, arg1)
	ret0, _ := ret[0].(*empty.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Publish indicates an expected call of Publish
func (mr *MockMessageBusServerMockRecorder) Publish(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockMessageBusServer)(nil).Publish), arg0, arg1)
}

// Subscribe mocks base method
func (m *MockMessageBusServer) Subscribe(arg0 *proto.SubscribeRequest, arg1 proto.MessageBus_SubscribeServer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Subscribe indicates an expected call of Subscribe
func (mr *MockMessageBusServerMockRecorder) Subscribe(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockMessageBusServer)(nil).Subscribe), arg0, arg1)
}

// MockMessageBus_SubscribeServer is a mock of MessageBus_SubscribeServer interface
type MockMessageBus_SubscribeServer struct {
	ctrl     *gomock.Controller
	recorder *MockMessageBus_SubscribeServerMockRecorder
}

// MockMessageBus_SubscribeServerMockRecorder is the mock recorder for MockMessageBus_SubscribeServer
type MockMessageBus_SubscribeServerMockRecorder struct {
	mock *MockMessageBus_SubscribeServer
}

// NewMockMessageBus_SubscribeServer creates a new mock instance
func NewMockMessageBus_SubscribeServer(ctrl *gomock.Controller) *MockMessageBus_SubscribeServer {
	mock := &MockMessageBus_SubscribeServer{ctrl: ctrl}
	mock.recorder = &MockMessageBus_SubscribeServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMessageBus_SubscribeServer) EXPECT() *MockMessageBus_SubscribeServerMockRecorder {
	return m.recorder
}

// Send mocks base method
func (m *MockMessageBus_SubscribeServer) Send(arg0 *proto.SubscribeResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send
func (mr *MockMessageBus_SubscribeServerMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockMessageBus_SubscribeServer)(nil).Send), arg0)
}

// SetHeader mocks base method
func (m *MockMessageBus_SubscribeServer) SetHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHeader indicates an expected call of SetHeader
func (mr *MockMessageBus_SubscribeServerMockRecorder) SetHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockMessageBus_SubscribeServer)(nil).SetHeader), arg0)
}

// SendHeader mocks base method
func (m *MockMessageBus_SubscribeServer) SendHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendHeader indicates an expected call of SendHeader
func (mr *MockMessageBus_SubscribeServerMockRecorder) SendHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendHeader", reflect.TypeOf((*MockMessageBus_SubscribeServer)(nil).SendHeader), arg0)
}

// SetTrailer mocks base method
func (m *MockMessageBus_SubscribeServer) SetTrailer(arg0 metadata.MD) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTrailer", arg0)
}

// SetTrailer indicates an expected call of SetTrailer
func (mr *MockMessageBus_SubscribeServerMockRecorder) SetTrailer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrailer", reflect.TypeOf((*MockMessageBus_SubscribeServer)(nil).SetTrailer), arg0)
}

// Context mocks base method
func (m *MockMessageBus_SubscribeServer) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context
func (mr *MockMessageBus_SubscribeServerMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockMessageBus_SubscribeServer)(nil).Context))
}

// SendMsg mocks base method
func (m_2 *MockMessageBus_SubscribeServer) SendMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg
func (mr *MockMessageBus_SubscribeServerMockRecorder) SendMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockMessageBus_SubscribeServer)(nil).SendMsg), m)
}

// RecvMsg mocks base method
func (m_2 *MockMessageBus_SubscribeServer) RecvMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg
func (mr *MockMessageBus_SubscribeServerMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockMessageBus_SubscribeServer)(nil).RecvMsg), m)
}
